---
title: "thlGraphs: other type of graphs"
author: "Salla Toikkanen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Other type of graphs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA
)
library(thlGraphs)
```

## Using thlTheme with some other graph types

How to use thlTheme() with other ggplot() -graphs, e.g scatter plot, pie and doughnut (cirle) charts 

### SCATTER PLOT
```{r scatter, fig.width=7, fig.height=4}
# Download the data
data("yli180")

# plot the data 
ggplot(data = yli180, aes(x = kk, y = pros)) + 
  geom_point(color = thlColors(n = 1, type = "quali", name="line"), 
             size = thlPtsConvert(10)) +
  thlTheme() + 
  thlYaxisControl(limits=c(0,2), lang = "eng") + 
  ylab("% -osuus")
thlPlotLogo(label = "",  x = .75, y = 0.03, size = .74, fontsize = 10)
```

### PIE AND DONUT CHARTS
```{r pie, fig.width=7, fig.height=5}
###############
## PIE CHART ##
###############

## Download the data
data("yli90")
yli90$AVI <- factor(yli90$AVI, labels=c("L채nsi- ja Sis채-Suomi",
         "Etel채-Suomi","It채-Suomi", "Lappi", 
         "Lounais-Suomi", "Pohjois-Suomi"))

## Some data manipulation:
# order the data accordingly
yli90 <- yli90[match(levels(yli90$AVI),yli90$AVI),]

# Calculate the % for 6/2018
yli90$`pros6/2018` <- (yli90$`6/2018`/sum(yli90$`6/2018`)*100)
# Round the % for 6/2018 to get nice labels
yli90$labels <- paste0(yli90$AVI, "\n", round(yli90$`pros6/2018`), " %")

## Draw plot:
# make first a blank barplot, use a dummy for the xvar (here "1")
bp <- thlBarPlot(data = yli90, xvar = 1, 
                 yvar = `pros6/2018`, groupvar = AVI, 
                colors = thlColors(n = nrow(yli90), type="quali", name = "line"), 
                ylabel = "",
                show.grid.y = FALSE, 
                yaxis.breaks = NULL,
                xaxis.breaks = NULL, base.size = 16) +
  thlAnnotate(type="label", x = 1.5, 
              y = cumsum(yli90$`pros6/2018`)- (yli90$`pros6/2018`/2), 
              label = yli90$labels, 
              text.size = 9, box.size = .2, fill = F)

## Make the pie chart and remove unwanted elements
bp + coord_polar("y", start = 0) + 
  theme(axis.title.y = element_blank(), 
        axis.line.x  = element_blank()) 
thlPlotLogo(label = "",  x = .75, y = 0.03, size = .74, fontsize = 10)


#################
## Donut chart ##
#################

## Data manipulation:
# Make a dummy data by adding a dummy x -variable
foodat<-data.frame(rbind(yli90[,c("pros6/2018", "AVI", "labels")],
                         yli90[,c("pros6/2018", "AVI", "labels")]),
                   x=rep(c(0,1),each = nrow(yli90)))
names(foodat)<-c("y","group", "labels", "x")

## Draw the chart
# Now create a blank barplot with two bars of which the left one is just empty 
foodat$y<-ifelse(foodat$x==0, 0, foodat$y)
bp2<-thlBarPlot(data = foodat, xvar = x, yvar = y, groupvar = group, 
                colors = thlColors(n = nrow(yli90), type="quali", name = "line"), 
                ylabel = "",
                show.grid.y = FALSE,  
                yaxis.breaks = NULL,
                xaxis.breaks = NULL,
                base.size = 16, 
                barwd = 0.6) + ## barwd controls how wide will the circle be
    thlAnnotate(type="label", x = 2.8, 
                y = cumsum(yli90$`pros6/2018`)- (yli90$`pros6/2018`/2), 
                label = yli90$labels, text.size = 9, 
                box.size = .2, fill = F)

# Ta-dah!
bp2 + coord_polar("y", start = 0) +
    theme(axis.title.y = element_blank(), 
          axis.line.x  = element_blank()) 
```
